################| Copy sensitive information, build image and deploy into instance group | ************************************
steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://$_BUCKET/*', '.']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/imagename:tag', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/imagename:tag']
- name: gcr.io/cloud-builders/gcloud
  args: [ compute, instance-groups, managed, rolling-action, replace,  <instance_group_name>, --region=asia-south1]

images: ['gcr.io/$PROJECT_ID/imagename:tag']
